### ISSUE TITLE
can we get a video of it working ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [bhikandeshmukh/MapEye#1]

**Comment by bhikandeshmukh** [comment]
Sure

**Comment by minanagehsalalma** [comment]
@bhikandeshmukh also bro i got an idea to get them to allow the location permission.

make the page show a button ( it can be anything) in the place where the allow the location permission pop up alert .. shows based on the device screen resolution ... then ask/get them to click on the button two clicks and on the second click trigger the permission so they click on it without noticing.

**Comment by bhikandeshmukh** [comment]
@minanagehsalalma give me demo code I will mention

**Comment by minanagehsalalma** [comment]
> give me demo code I will mention

@bhikandeshmukh i don't have one currently 

but here is something similar used to get users to allow notifications without noticing 

you try to click skip ad 
![image](https://user-images.githubusercontent.com/20546638/107368117-d301ce80-6ae8-11eb-9cf9-4c81a4655537.png)

but this pops at the same time 
![image](https://user-images.githubusercontent.com/20546638/107368393-2d029400-6ae9-11eb-9c70-3d4079c45aa2.png)
which makes you click on it without noticing

also if you click block ... it will redirect you to another sub domain 
![image](https://user-images.githubusercontent.com/20546638/107368499-4c012600-6ae9-11eb-8769-507e4c0b3c0d.png)

[The link 
](https://1.nbryb.com/tag3_2_cloud_zoneid_15_tst3.html?ymid=16119587242630631464055902705693926&zoneid=3599375&sourceid=1221182) .test it on a mobile device using chrome browser.

**Comment by bhikandeshmukh** [comment]
Ok I'll try

**Comment by minanagehsalalma** [comment]
@bhikandeshmukh completed ,where ? 
![image](https://user-images.githubusercontent.com/20546638/192903695-d66ad0d6-5e4c-4627-8603-40709826653f.png)
